#############################################################################
# Makefile for building: qmarkdown
# Generated by qmake (3.1) (Qt 5.15.1) modified by Peter Konnerup Moss
# Project:  qmarkdown.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qmarkdown.pro
#############################################################################

####### Compiler, tools and options

CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB
CXXFLAGS      = -pipe -O3 -Wall -Wextra -D_REENTRANT -fPIC -std=c++20 $(DEFINES)
INCPATH       = -I. -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtQuick -I/usr/include/qt/QtPrintSupport -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtQmlModels -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtQml -I/usr/include/qt/QtNetwork -I/usr/include/qt/QtPositioning -I/usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
DEL_FILE      = rm -f
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt5WebEngineWidgets.so /usr/lib/libQt5WebEngineCore.so /usr/lib/libQt5Quick.so /usr/lib/libQt5PrintSupport.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5QmlModels.so /usr/lib/libQt5WebChannel.so /usr/lib/libQt5Qml.so /usr/lib/libQt5Network.so /usr/lib/libQt5Positioning.so /usr/lib/libQt5Core.so -lGL -lpthread   
STRIP         = strip
MOCS = moc_predefs.h \
       moc_mainwindow.cpp \
       moc_document.cpp \
       moc_preview.cpp
MOC_CMD = /usr/bin/moc $(DEFINES) --include \
      /home/peter/git/qmarkdown/moc_predefs.h \
      -I/usr/lib/qt/mkspecs/linux-g++ \
      -I/home/peter/git/qmarkdown \
      -I/usr/include/qt \
      -I/usr/include/qt/QtWebEngineWidgets \
      -I/usr/include/qt/QtWebEngineCore \
      -I/usr/include/qt/QtQuick \
      -I/usr/include/qt/QtPrintSupport \
      -I/usr/include/qt/QtWidgets \
      -I/usr/include/qt/QtGui \
      -I/usr/include/qt/QtQmlModels \
      -I/usr/include/qt/QtWebChannel \
      -I/usr/include/qt/QtQml \
      -I/usr/include/qt/QtNetwork \
      -I/usr/include/qt/QtPositioning \
      -I/usr/include/qt/QtCore \
      -I/usr/include/c++/10.2.0 \
      -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu \
      -I/usr/include/c++/10.2.0/backward \
      -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include \
      -I/usr/local/include \
      -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed \
      -I/usr/include

####### Files

SOURCES = main.cpp \
		mainwindow.cpp \
		document.cpp \
		preview.cpp qrc_qmarkdown.cpp \
		moc_mainwindow.cpp \
		moc_document.cpp \
		moc_preview.cpp \
        resgen.cpp
OBJECTS = main.o \
		mainwindow.o \
		document.o \
		preview.o \
		qrc_qmarkdown.o \
		moc_mainwindow.o \
		moc_document.o \
		moc_preview.o \
		helpers.o \
        resgen.o
TARGET = qmarkdown

####### Build rules

all: qmarkdown qrc_qmarkdown.cpp $(MOCS)

qmarkdown:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) moc_mainwindow.cpp moc_document.cpp moc_preview.cpp
	-$(DEL_FILE) qrc_qmarkdown.cpp
	-$(DEL_FILE) moc_predefs.h

####### Sub-libraries

RESOURCES = resources/qmarkdown.qrc \
            resources/help.md \
            resources/index.html \
            resources/3rdparty/markdown.css \
            resources/3rdparty/marked.js

qrc_qmarkdown.cpp: $(RESOURCES) /usr/bin/rcc
	/usr/bin/rcc -name qmarkdown resources/qmarkdown.qrc -o qrc_qmarkdown.cpp

moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

moc_mainwindow.cpp: mainwindow.h \
                    document.h \
                    preview.h \
                    moc_predefs.h \
                    /usr/bin/moc
	$(MOC_CMD) mainwindow.h -o moc_mainwindow.cpp

moc_document.cpp: document.h \
                  moc_predefs.h \
                  /usr/bin/moc 
	$(MOC_CMD) document.h -o moc_document.cpp

moc_preview.cpp: preview.h \
                 moc_predefs.h \
                 /usr/bin/moc
	$(MOC_CMD) preview.h -o moc_preview.cpp

####### Compile

main.o: main.cpp mainwindow.h \
		document.h \
		preview.h \
        helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		document.h \
		preview.h \
        helpers.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

resgen.o: resgen.cpp resgen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resgen.o resgen.cpp

helpers.o: helpers.cpp helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpers.o helpers.cpp

document.o: document.cpp document.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o document.cpp

preview.o: preview.cpp preview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preview.o preview.cpp

qrc_qmarkdown.o: qrc_qmarkdown.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmarkdown.o qrc_qmarkdown.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_document.o: moc_document.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_document.o moc_document.cpp

moc_preview.o: moc_preview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preview.o moc_preview.cpp

####### Install

install: all
	mkdir -p $(DESTDIR)${PREFIX}/bin
	$(INSTALL_PROGRAM) $(TARGET) $(DESTDIR)${PREFIX}/bin/$(TARGET)
	-$(STRIP) ${DESTDIR}${PREFIX}/bin/$(TARGET)

uninstall:
	-$(DEL_FILE) ${DESTDIR}${PREFIX}/bin/$(TARGET)
