#############################################################################
# Makefile for building: qmarkdown
# Generated by qmake (3.1) (Qt 5.15.1) modified by Peter Konnerup Moss
# Project:  qmarkdown.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile qmarkdown.pro
#############################################################################

####### Compiler, tools and options

CXX           = g++
CXXFLAGS      = -O3 -Wall -Wextra -fPIC -std=c++20
INCPATH       = -I. -I./src -I/usr/include/qt -I/usr/include/qt/QtWebEngineWidgets -I/usr/include/qt/QtWebEngineCore -I/usr/include/qt/QtWidgets -I/usr/include/qt/QtGui -I/usr/include/qt/QtWebChannel -I/usr/include/qt/QtCore
DEL_FILE      = rm -f
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
LINK          = g++
SRCDIR        = src
BUILDDIR      = build
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib
LIBS          = /usr/lib/libQt5WebEngineWidgets.so /usr/lib/libQt5WebEngineCore.so /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5WebChannel.so /usr/lib/libQt5Core.so -lGL -lpthread   

####### MOC

MOCS = moc_predefs.h \
       moc_mainwindow.cpp \
       moc_document.cpp \
       moc_preview.cpp
MOC_CMD = /usr/bin/moc --include \
      $(BUILDDIR)/moc_predefs.h \
	  -I. \
      -I/usr/lib/qt/mkspecs/linux-g++ \
      -I/usr/include/qt \
      -I/usr/include/qt/QtWebEngineWidgets \
      -I/usr/include/qt/QtWebEngineCore \
      -I/usr/include/qt/QtWidgets \
      -I/usr/include/qt/QtGui \
      -I/usr/include/qt/QtWebChannel \
      -I/usr/include/qt/QtCore \
      -I/usr/include/c++/10.2.0 \
      -I/usr/include/c++/10.2.0/x86_64-pc-linux-gnu \
      -I/usr/include/c++/10.2.0/backward \
      -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include \
      -I/usr/local/include \
      -I/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/include-fixed \
      -I/usr/include

####### Files

SOURCES = $(SRCDIR)/main.cpp \
		$(SRCDIR)/mainwindow.cpp \
		$(SRCDIR)/document.cpp \
		$(SRCDIR)/preview.cpp \
        $(SRCDIR)/resgen.cpp \
		qrc_qmarkdown.cpp \
		moc_mainwindow.cpp \
		moc_document.cpp \
		moc_preview.cpp

OBJECTS = main.o \
		mainwindow.o \
		document.o \
		preview.o \
		qrc_qmarkdown.o \
		moc_mainwindow.o \
		moc_document.o \
		moc_preview.o \
		helpers.o \
        resgen.o
TARGET = qmarkdown

####### Build rules

all: qmarkdown qrc_qmarkdown.cpp $(MOCS)

qmarkdown:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) moc_mainwindow.cpp moc_document.cpp moc_preview.cpp
	-$(DEL_FILE) qrc_qmarkdown.cpp
	-$(DEL_FILE) moc_predefs.h

####### Sub-libraries

RESOURCES = $(SRCDIR)/resources/qmarkdown.qrc \
            $(SRCDIR)/resources/help.md \
            $(SRCDIR)/resources/index.html \
            $(SRCDIR)/resources/3rdparty/markdown.css \
            $(SRCDIR)/resources/3rdparty/marked.js

qrc_qmarkdown.cpp: $(RESOURCES) /usr/bin/rcc
	/usr/bin/rcc -name qmarkdown $(SRCDIR)/resources/qmarkdown.qrc -o qrc_qmarkdown.cpp

moc_predefs.h: /usr/lib/qt/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt/mkspecs/features/data/dummy.cpp

moc_mainwindow.cpp: $(SRCDIR)/mainwindow.h \
                    $(SRCDIR)/document.h \
                    $(SRCDIR)/preview.h \
                    moc_predefs.h \
                    /usr/bin/moc
	$(MOC_CMD) $(SRCDIR)/mainwindow.h -o moc_mainwindow.cpp

moc_document.cpp: $(SRCDIR)/document.h \
                  moc_predefs.h \
                  /usr/bin/moc 
	$(MOC_CMD) $(SRCDIR)/document.h -o moc_document.cpp

moc_preview.cpp: $(SRCDIR)/preview.h \
                 moc_predefs.h \
                 /usr/bin/moc
	$(MOC_CMD) $(SRCDIR)/preview.h -o moc_preview.cpp

####### Compile

main.o: $(SRCDIR)/main.cpp \
        $(SRCDIR)/mainwindow.h \
		$(SRCDIR)/document.h \
		$(SRCDIR)/preview.h \
        $(SRCDIR)/helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o $(SRCDIR)/main.cpp

mainwindow.o: $(SRCDIR)/mainwindow.cpp \
        $(SRCDIR)/mainwindow.h \
		$(SRCDIR)/document.h \
		$(SRCDIR)/preview.h \
        $(SRCDIR)/helpers.h \
		$(SRCDIR)/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o $(SRCDIR)/mainwindow.cpp

resgen.o: $(SRCDIR)/resgen.cpp $(SRCDIR)/resgen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resgen.o $(SRCDIR)/resgen.cpp

helpers.o: $(SRCDIR)/helpers.cpp $(SRCDIR)/helpers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o helpers.o $(SRCDIR)/helpers.cpp

document.o: $(SRCDIR)/document.cpp $(SRCDIR)/document.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o document.o $(SRCDIR)/document.cpp

preview.o: $(SRCDIR)/preview.cpp $(SRCDIR)/preview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preview.o $(SRCDIR)/preview.cpp

qrc_qmarkdown.o: qrc_qmarkdown.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmarkdown.o qrc_qmarkdown.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_document.o: moc_document.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_document.o moc_document.cpp

moc_preview.o: moc_preview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preview.o moc_preview.cpp

####### Install

install: all
	mkdir -p $(DESTDIR)$(PREFIX)/bin
	$(INSTALL_PROGRAM) $(TARGET) $(DESTDIR)$(PREFIX)/bin/$(TARGET)
	-strip $(DESTDIR)$(PREFIX)/bin/$(TARGET)

uninstall:
	-$(DEL_FILE) $(DESTDIR)$(PREFIX)/bin/$(TARGET)
